# Generated by Django 4.2 on 2026-02-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.CharField(blank=True, help_text='e.g., 10:00 AM - 5:00 PM', max_length=100, null=True)),
                ('location', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('Conference', 'Conference'), ('Workshop', 'Workshop'), ('Symposium', 'Symposium'), ('Seminar', 'Seminar'), ('Webinar', 'Webinar'), ('Panel Discussion', 'Panel Discussion'), ('Recruitment', 'Recruitment'), ('Milestone', 'Milestone'), ('Other', 'Other')], default='Workshop', max_length=50)),
                ('attendees', models.PositiveIntegerField(default=0, help_text='Expected or actual number of attendees')),
                ('registration_deadline', models.DateField(blank=True, null=True)),
                ('speakers', models.TextField(blank=True, help_text='Comma-separated list of speakers', null=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='events/banners/')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this event prominently')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-date'],
            },
        ),
    ]
