# Generated by Django 4.2 on 2026-02-02 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('success_message', models.TextField(default='Thank you for your submission!', help_text='Message shown after successful submission')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Form',
                'verbose_name_plural': 'Forms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='forms_builder.form')),
            ],
            options={
                'verbose_name': 'Form Submission',
                'verbose_name_plural': 'Form Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('number', 'Number'), ('phone', 'Phone'), ('textarea', 'Text Area'), ('select', 'Dropdown Select'), ('radio', 'Radio Buttons'), ('checkbox', 'Checkbox'), ('checkbox_group', 'Checkbox Group'), ('file', 'File Upload'), ('image', 'Image Upload'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'Date & Time'), ('url', 'URL')], default='text', max_length=20)),
                ('placeholder', models.CharField(blank=True, max_length=255, null=True)),
                ('help_text', models.CharField(blank=True, max_length=500, null=True)),
                ('required', models.BooleanField(default=False)),
                ('choices', models.TextField(blank=True, help_text='For select, radio, checkbox_group: Enter choices separated by new lines', null=True)),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('min_value', models.IntegerField(blank=True, help_text='For number fields', null=True)),
                ('max_value', models.IntegerField(blank=True, help_text='For number fields', null=True)),
                ('max_length', models.IntegerField(blank=True, help_text='For text fields', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms_builder.form')),
            ],
            options={
                'verbose_name': 'Form Field',
                'verbose_name_plural': 'Form Fields',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='form_uploads/%Y/%m/')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms_builder.formfield')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='forms_builder.formsubmission')),
            ],
            options={
                'verbose_name': 'Field Value',
                'verbose_name_plural': 'Field Values',
            },
        ),
    ]
